length = int(input("Enter Length :"))
breadth = int(input("Enter Breadth :"))
side = int(input("Enter Side of Square :"))
radius = int(input("Enter Radius of Circle :"))
print("Area of Rectangle is :",length*breadth)
print("Perimeter of Rectangle is :",2*(length+breadth))
print("Area of Square is ",side*side)
print("Perimeter of Square is :",4*side)
print("Area of Circle is ",3.14*radius*radius)
print("Circumference of Circle is ",2*3.14*radius)